### ISSUE TITLE
Segmentation fault in ethaddrgen

### ISSUE THREAD

**Issue by nyw0102** [Limeth/ethaddrgen#9]
### Version

Latest

### Description

There is an segmentation fault bug in the function "atomic_load". It seems that this crash is cause by trying to pop the value in the empty queue

### Current Behavior

ASAN detect segmentation fault in read the value at address 0x000000000820 in my machine. 

```AddressSanitizer:DEADLYSIGNAL
=================================================================
==2393815==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000820 (pc 0x56374634a604 bp 0x153eff5f2350 sp 0x153eff5f21e0 T2)
==2393815==The signal is caused by a READ memory access.
==2393815==Hint: address points to the zero page.
    #0 0x56374634a604 in core::sync::atomic::atomic_load::h6cbe6a7ea4f99ff8 /home/nyw0102/s2fuzz/scripts/rust/library/core/src/sync/atomic.rs:2629:24
    #1 0x5637462c4a41 in core::sync::atomic::AtomicUsize::load::h334b60e61284b02e /home/nyw0102/s2fuzz/scripts/rust/library/core/src/sync/atomic.rs:1755:26
    #2 0x5637462fb070 in crossbeam_epoch::atomic::Atomic$LT$T$GT$::load::he0d6f0d4ac9b03ba /home/nyw0102/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.3.0/src/atomic.rs:208:36
    #3 0x563746325927 in crossbeam_epoch::sync::queue::Queue$LT$T$GT$::pop_internal::h280e927a26120ee1 /home/nyw0102/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.3.0/src/sync/queue.rs:117:20
    #4 0x563746325927 in crossbeam_epoch::sync::queue::Queue$LT$T$GT$::try_pop::h4d153a926cc656d3 /home/nyw0102/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.3.0/src/sync/queue.rs:162:31
    #5 0x563746328ebe in _$LT$crossbeam_epoch..sync..queue..Queue$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::hde7352d697ca6cae /home/nyw0102/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.3.0/src/sync/queue.rs:190:33
    #6 0x5637462b4893 in core::ptr::drop_in_place$LT$crossbeam_epoch..sync..queue..Queue$LT$$LP$crossbeam_epoch..epoch..Epoch$C$crossbeam_epoch..garbage..Bag$RP$$GT$$GT$::hc4e76d2ba4bb2d65 /home/nyw0102/s2fuzz/scripts/rust/library/core/src/ptr/mod.rs:487:1
    #7 0x56374632124a in crossbeam_epoch::sync::queue::Queue$LT$T$GT$::new::h99bcef60c86387f9 /home/nyw0102/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.3.0/src/sync/queue.rs:67:5
    #8 0x56374631067e in crossbeam_epoch::internal::Global::new::he84ceefb1e95350e /home/nyw0102/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.3.0/src/internal.rs:63:20
    #9 0x563746302bab in crossbeam_epoch::collector::Collector::new::hc552cfdef81c30c1 /home/nyw0102/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.3.0/src/collector.rs:32:38
    #10 0x5637462b1999 in _$LT$crossbeam_epoch..default..COLLECTOR$u20$as$u20$core..ops..deref..Deref$GT$::deref::__static_ref_initialize::ha254f3597f8b292c /home/nyw0102/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-epoch-0.3.0/src/default.rs:12:39
    #11 0x5637462b1999 in core::ops::function::FnOnce::call_once::he0c56d7fa81b5fc3 /home/nyw0102/s2fuzz/scripts/rust/library/core/src/ops/function.rs:248:5
    #12 0x56374629ca39 in lazy_static::lazy::Lazy$LT$T$GT$::get::_$u7b$$u7b$closure$u7d$$u7d$::h48363612c7781c1b /home/nyw0102/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-0.2.11/src/lazy.rs:24:45
    #13 0x5637462a12da in std::sync::once::Once::call_once::_$u7b$$u7b$closure$u7d$$u7d$::ha2f956f75897fc17 /home/nyw0102/s2fuzz/scripts/rust/library/std/src/sync/once.rs:276:41
    #14 0x5637451de585 in regex::dfa::Fsm::exec_at_reverse::h3188031557dfaa79 /home/nyw0102/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.6/src/dfa.rs
    #15 0x5637451de585 in regex::dfa::Fsm::reverse::h48c5fef66f894860 /home/nyw0102/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.6/src/dfa.rs:521:9
    #16 0x5637451de585 in regex::exec::ExecNoSync::find_dfa_forward::h4aa3777b347f2072 /home/nyw0102/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.6/src/exec.rs:651:15
    #17 0x5637451de585 in _$LT$regex..exec..ExecNoSync$u20$as$u20$regex..re_trait..RegularExpression$GT$::find_at::h2076a1f8c9da5659 /home/nyw0102/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.2.6/src/exec.rs:482:23
.
.
.
```

### Expected Behavior

Memory-safety code with no segmentation fault

### Additional Information

I'll attach a bug report about this crash
[Ethaddrgen Crash Report.docx](https://github.com/user-attachments/files/16797888/Ethaddrgen.Crash.Report.docx)

**Comment by nyw0102** [comment]
Hi! I hope you have great time in this year. 

Anyway, I think this error might have an impact on the memory safety in "ethaddrgen" and also to users.

If you don't mind, it would be great to take this error into account! Thanks!
